# ^..^ ~ made by @sebiram

format = """
[/ᐠ - ˕ -マ ](white)\
$nodejs\
$rust\
$python\
$cmake\
$golang\
$java\
$kotlin\
$lua\
$cmd_duration\
\n\
$directory\
$git_branch\
$git_status\
$character\
"""

[directory]
format = "[$path ](#85A0FF)"
truncation_length = 3
truncation_symbol = '/'

[git_branch]
format = '[git:\([$branch(:$remote_branch)](white)\)](#f1502f)'

[git_status]
format = "[$all_status$ahead_behind ]($style)"
modified = '[*](#f1502f)'
deleted = ''
untracked = ''
staged = ''
renamed = ''
diverged = ''
conflicted = ''
ahead = ''
behind = ''

[cmake]
format = '[clang $version ]($style)'

[golang]
format = '[go $version ]($style)'

[java]
format = '[java $version ](#F89917)'

[kotlin]
format = '[kt $version ]($style)'

[lua]
format = '[lua $version ]($style)'

[nodejs]
format = '[node $version ](#88F75C)'

[python]
format = '[py $version ](#FFD343)'

[rust]
format = '[rs $version ](#CE422B)'

[cmd_duration]
format = '[$duration](white)'

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](red)'
